# Generated by Django 4.1.3 on 2023-01-17 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='token',
            new_name='activation_token',
        ),
    ]
