# Generated by Django 4.1.3 on 2023-02-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_music_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
