# Generated by Django 4.1.3 on 2023-01-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_token_profile_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
