# Generated by Django 4.1.3 on 2023-02-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_music_user_alter_music_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
