# Generated by Django 4.1.3 on 2023-01-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_music_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.ImageField(blank=True, default='image/4762573.jpg', null=True, upload_to='image/'),
        ),
    ]
