# Generated by Django 4.1.3 on 2023-02-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_notifications_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='seen',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
