# Generated by Django 4.1.3 on 2023-02-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_notifications_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='image/4762573.jpg', null=True, upload_to='image/users_img'),
        ),
    ]
