# Generated by Django 4.1.3 on 2023-02-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_music_package_alter_userpackage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpackage',
            name='txref',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
